# cc_test(
#     name = "hashmap",
#     size = "small",
#     srcs = glob([
#         "*.c",
#     ]),
#     features = ["treat_warnings_as_errors"],
#     deps = [
#         "//source/cortecs/stdlib/hashmap",
#         "@unity",
#     ],
# )
