cc_test(
    name = "hashmap",
    size = "small",
    srcs = glob([
        "*.c",
        "*.h",
    ]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/cortecs/stdlib/hashmap",
        "@unity",
    ],
)
