cc_test(
    name = "string",
    size = "small",
    srcs = glob([
        "*.c",
    ]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/cortecs/string",
        "@unity",
    ],
)
