#ifndef CORTECS_LEXER_TEST_TEST_CONFIGS_H
#define CORTECS_LEXER_TEST_TEST_CONFIGS_H

#include "test_impls.h"

extern cortecs_lexer_test_config_t cortecs_lexer_test_space_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_name_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_type_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_float_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_bad_float_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_int_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_bad_int_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_invalid_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_new_line_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_open_paren_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_close_paren_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_open_curly_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_close_curly_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_open_square_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_close_square_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_single_quote_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_double_quote_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_back_quote_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_function_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_let_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_return_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_if_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_operator_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_comma_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_colon_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_semicolon_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_dot_config;

#endif