cc_test(
    name = "common",
    size = "small",
    srcs = glob([
        "*.c",
        "*.h",
    ]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/common",
        "@unity",
    ],
)
