#ifndef CORTECS_LEXER_TEST_TEST_CONFIGS_H
#define CORTECS_LEXER_TEST_TEST_CONFIGS_H

#include "test_impls.h"

extern cortecs_lexer_test_config_t cortecs_lexer_test_space_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_name_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_type_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_float_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_bad_float_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_int_config;
extern cortecs_lexer_test_config_t cortecs_lexer_test_bad_int_config;

#endif