cc_test(
    name = "arena",
    size = "small",
    srcs = glob([
        "*.c",
    ]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/cortecs/arena",
        "@unity",
    ],
)
