#ifndef CORTECS_FUNCTION_FUNCTION_H
#define CORTECS_FUNCTION_FUNCTION_H

#include <common.h>

// I have no idea why I need CONCAT_3 here but it doesn't work if using overloaded CONCAT.
#define cortecs_mangle_args_1(arg0) arg0
#define cortecs_mangle_args_2(arg0, arg1) CONCAT_3(arg0, _0, arg1)
#define cortecs_mangle_args_3(arg0, arg1, ...) cortecs_mangle_args_2(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_4(arg0, arg1, ...) cortecs_mangle_args_3(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_5(arg0, arg1, ...) cortecs_mangle_args_4(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_6(arg0, arg1, ...) cortecs_mangle_args_5(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_7(arg0, arg1, ...) cortecs_mangle_args_6(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_8(arg0, arg1, ...) cortecs_mangle_args_7(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_9(arg0, arg1, ...) cortecs_mangle_args_8(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_10(arg0, arg1, ...) cortecs_mangle_args_9(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_11(arg0, arg1, ...) cortecs_mangle_args_10(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_12(arg0, arg1, ...) cortecs_mangle_args_11(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_13(arg0, arg1, ...) cortecs_mangle_args_12(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_14(arg0, arg1, ...) cortecs_mangle_args_13(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_15(arg0, arg1, ...) cortecs_mangle_args_14(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_16(arg0, arg1, ...) cortecs_mangle_args_15(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_17(arg0, arg1, ...) cortecs_mangle_args_16(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_18(arg0, arg1, ...) cortecs_mangle_args_17(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_19(arg0, arg1, ...) cortecs_mangle_args_18(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_20(arg0, arg1, ...) cortecs_mangle_args_19(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_21(arg0, arg1, ...) cortecs_mangle_args_20(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_22(arg0, arg1, ...) cortecs_mangle_args_21(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_23(arg0, arg1, ...) cortecs_mangle_args_22(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_24(arg0, arg1, ...) cortecs_mangle_args_23(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_25(arg0, arg1, ...) cortecs_mangle_args_24(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_26(arg0, arg1, ...) cortecs_mangle_args_25(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_27(arg0, arg1, ...) cortecs_mangle_args_26(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_28(arg0, arg1, ...) cortecs_mangle_args_27(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_29(arg0, arg1, ...) cortecs_mangle_args_28(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_30(arg0, arg1, ...) cortecs_mangle_args_29(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_31(arg0, arg1, ...) cortecs_mangle_args_30(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_32(arg0, arg1, ...) cortecs_mangle_args_31(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_33(arg0, arg1, ...) cortecs_mangle_args_32(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_34(arg0, arg1, ...) cortecs_mangle_args_33(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_35(arg0, arg1, ...) cortecs_mangle_args_34(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_36(arg0, arg1, ...) cortecs_mangle_args_35(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_37(arg0, arg1, ...) cortecs_mangle_args_36(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_38(arg0, arg1, ...) cortecs_mangle_args_37(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_39(arg0, arg1, ...) cortecs_mangle_args_38(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_40(arg0, arg1, ...) cortecs_mangle_args_39(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_41(arg0, arg1, ...) cortecs_mangle_args_40(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_42(arg0, arg1, ...) cortecs_mangle_args_41(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_43(arg0, arg1, ...) cortecs_mangle_args_42(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_44(arg0, arg1, ...) cortecs_mangle_args_43(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_45(arg0, arg1, ...) cortecs_mangle_args_44(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_46(arg0, arg1, ...) cortecs_mangle_args_45(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_47(arg0, arg1, ...) cortecs_mangle_args_46(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_48(arg0, arg1, ...) cortecs_mangle_args_47(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_49(arg0, arg1, ...) cortecs_mangle_args_48(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_50(arg0, arg1, ...) cortecs_mangle_args_49(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_51(arg0, arg1, ...) cortecs_mangle_args_50(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_52(arg0, arg1, ...) cortecs_mangle_args_51(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_53(arg0, arg1, ...) cortecs_mangle_args_52(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_54(arg0, arg1, ...) cortecs_mangle_args_53(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_55(arg0, arg1, ...) cortecs_mangle_args_54(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_56(arg0, arg1, ...) cortecs_mangle_args_55(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_57(arg0, arg1, ...) cortecs_mangle_args_56(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_58(arg0, arg1, ...) cortecs_mangle_args_57(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_59(arg0, arg1, ...) cortecs_mangle_args_58(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_60(arg0, arg1, ...) cortecs_mangle_args_59(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_61(arg0, arg1, ...) cortecs_mangle_args_60(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_62(arg0, arg1, ...) cortecs_mangle_args_61(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args_63(arg0, arg1, ...) cortecs_mangle_args_62(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_args(...) OVERLOADED_MACRO_0(cortecs_mangle_args_, __VA_ARGS__)

#define cortecs_mangle_name_2(arg0, arg1) CONCAT_3(arg0, _, arg1)
#define cortecs_mangle_name_3(arg0, arg1, ...) cortecs_mangle_name_2(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_4(arg0, arg1, ...) cortecs_mangle_name_3(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_5(arg0, arg1, ...) cortecs_mangle_name_4(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_6(arg0, arg1, ...) cortecs_mangle_name_5(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_7(arg0, arg1, ...) cortecs_mangle_name_6(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_8(arg0, arg1, ...) cortecs_mangle_name_7(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_9(arg0, arg1, ...) cortecs_mangle_name_8(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_10(arg0, arg1, ...) cortecs_mangle_name_9(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_11(arg0, arg1, ...) cortecs_mangle_name_10(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_12(arg0, arg1, ...) cortecs_mangle_name_11(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_13(arg0, arg1, ...) cortecs_mangle_name_12(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_14(arg0, arg1, ...) cortecs_mangle_name_13(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_15(arg0, arg1, ...) cortecs_mangle_name_14(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_16(arg0, arg1, ...) cortecs_mangle_name_15(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_17(arg0, arg1, ...) cortecs_mangle_name_16(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_18(arg0, arg1, ...) cortecs_mangle_name_17(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_19(arg0, arg1, ...) cortecs_mangle_name_18(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_20(arg0, arg1, ...) cortecs_mangle_name_19(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_21(arg0, arg1, ...) cortecs_mangle_name_20(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_22(arg0, arg1, ...) cortecs_mangle_name_21(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_23(arg0, arg1, ...) cortecs_mangle_name_22(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_24(arg0, arg1, ...) cortecs_mangle_name_23(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_25(arg0, arg1, ...) cortecs_mangle_name_24(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_26(arg0, arg1, ...) cortecs_mangle_name_25(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_27(arg0, arg1, ...) cortecs_mangle_name_26(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_28(arg0, arg1, ...) cortecs_mangle_name_27(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_29(arg0, arg1, ...) cortecs_mangle_name_28(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_30(arg0, arg1, ...) cortecs_mangle_name_29(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_31(arg0, arg1, ...) cortecs_mangle_name_30(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_32(arg0, arg1, ...) cortecs_mangle_name_31(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_33(arg0, arg1, ...) cortecs_mangle_name_32(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_34(arg0, arg1, ...) cortecs_mangle_name_33(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_35(arg0, arg1, ...) cortecs_mangle_name_34(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_36(arg0, arg1, ...) cortecs_mangle_name_35(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_37(arg0, arg1, ...) cortecs_mangle_name_36(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_38(arg0, arg1, ...) cortecs_mangle_name_37(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_39(arg0, arg1, ...) cortecs_mangle_name_38(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_40(arg0, arg1, ...) cortecs_mangle_name_39(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_41(arg0, arg1, ...) cortecs_mangle_name_40(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_42(arg0, arg1, ...) cortecs_mangle_name_41(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_43(arg0, arg1, ...) cortecs_mangle_name_42(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_44(arg0, arg1, ...) cortecs_mangle_name_43(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_45(arg0, arg1, ...) cortecs_mangle_name_44(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_46(arg0, arg1, ...) cortecs_mangle_name_45(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_47(arg0, arg1, ...) cortecs_mangle_name_46(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_48(arg0, arg1, ...) cortecs_mangle_name_47(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_49(arg0, arg1, ...) cortecs_mangle_name_48(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_50(arg0, arg1, ...) cortecs_mangle_name_49(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_51(arg0, arg1, ...) cortecs_mangle_name_50(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_52(arg0, arg1, ...) cortecs_mangle_name_51(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_53(arg0, arg1, ...) cortecs_mangle_name_52(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_54(arg0, arg1, ...) cortecs_mangle_name_53(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_55(arg0, arg1, ...) cortecs_mangle_name_54(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_56(arg0, arg1, ...) cortecs_mangle_name_55(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_57(arg0, arg1, ...) cortecs_mangle_name_56(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_58(arg0, arg1, ...) cortecs_mangle_name_57(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_59(arg0, arg1, ...) cortecs_mangle_name_58(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_60(arg0, arg1, ...) cortecs_mangle_name_59(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_61(arg0, arg1, ...) cortecs_mangle_name_60(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_62(arg0, arg1, ...) cortecs_mangle_name_61(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_63(arg0, arg1, ...) cortecs_mangle_name_62(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_name(...) OVERLOADED_MACRO_0(cortecs_mangle_name_, __VA_ARGS__)

// I also have no idea why it all works here. the C macro system is quite lovely...
#define cortecs_type_args(name, ...) CONCAT(name, _1, cortecs_mangle_args(__VA_ARGS__), _2)

#endif