#ifndef CORTECS_FUNCTION_FUNCTION_H
#define CORTECS_FUNCTION_FUNCTION_H

#include <common.h>

// I have no idea why I need CONCAT_3 here but it doesn't work if using overloaded CONCAT.
#define cortecs_mangle_params_1(arg0) arg0
#define cortecs_mangle_params_2(arg0, arg1) CONCAT_3(arg0, _0, arg1)
#define cortecs_mangle_params_3(arg0, arg1, ...) cortecs_mangle_params_2(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_4(arg0, arg1, ...) cortecs_mangle_params_3(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_5(arg0, arg1, ...) cortecs_mangle_params_4(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_6(arg0, arg1, ...) cortecs_mangle_params_5(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_7(arg0, arg1, ...) cortecs_mangle_params_6(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_8(arg0, arg1, ...) cortecs_mangle_params_7(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_9(arg0, arg1, ...) cortecs_mangle_params_8(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_10(arg0, arg1, ...) cortecs_mangle_params_9(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_11(arg0, arg1, ...) cortecs_mangle_params_10(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_12(arg0, arg1, ...) cortecs_mangle_params_11(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_13(arg0, arg1, ...) cortecs_mangle_params_12(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_14(arg0, arg1, ...) cortecs_mangle_params_13(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_15(arg0, arg1, ...) cortecs_mangle_params_14(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_16(arg0, arg1, ...) cortecs_mangle_params_15(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_17(arg0, arg1, ...) cortecs_mangle_params_16(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_18(arg0, arg1, ...) cortecs_mangle_params_17(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_19(arg0, arg1, ...) cortecs_mangle_params_18(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_20(arg0, arg1, ...) cortecs_mangle_params_19(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_21(arg0, arg1, ...) cortecs_mangle_params_20(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_22(arg0, arg1, ...) cortecs_mangle_params_21(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_23(arg0, arg1, ...) cortecs_mangle_params_22(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_24(arg0, arg1, ...) cortecs_mangle_params_23(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_25(arg0, arg1, ...) cortecs_mangle_params_24(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_26(arg0, arg1, ...) cortecs_mangle_params_25(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_27(arg0, arg1, ...) cortecs_mangle_params_26(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_28(arg0, arg1, ...) cortecs_mangle_params_27(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_29(arg0, arg1, ...) cortecs_mangle_params_28(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_30(arg0, arg1, ...) cortecs_mangle_params_29(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_31(arg0, arg1, ...) cortecs_mangle_params_30(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_32(arg0, arg1, ...) cortecs_mangle_params_31(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_33(arg0, arg1, ...) cortecs_mangle_params_32(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_34(arg0, arg1, ...) cortecs_mangle_params_33(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_35(arg0, arg1, ...) cortecs_mangle_params_34(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_36(arg0, arg1, ...) cortecs_mangle_params_35(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_37(arg0, arg1, ...) cortecs_mangle_params_36(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_38(arg0, arg1, ...) cortecs_mangle_params_37(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_39(arg0, arg1, ...) cortecs_mangle_params_38(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_40(arg0, arg1, ...) cortecs_mangle_params_39(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_41(arg0, arg1, ...) cortecs_mangle_params_40(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_42(arg0, arg1, ...) cortecs_mangle_params_41(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_43(arg0, arg1, ...) cortecs_mangle_params_42(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_44(arg0, arg1, ...) cortecs_mangle_params_43(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_45(arg0, arg1, ...) cortecs_mangle_params_44(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_46(arg0, arg1, ...) cortecs_mangle_params_45(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_47(arg0, arg1, ...) cortecs_mangle_params_46(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_48(arg0, arg1, ...) cortecs_mangle_params_47(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_49(arg0, arg1, ...) cortecs_mangle_params_48(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_50(arg0, arg1, ...) cortecs_mangle_params_49(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_51(arg0, arg1, ...) cortecs_mangle_params_50(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_52(arg0, arg1, ...) cortecs_mangle_params_51(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_53(arg0, arg1, ...) cortecs_mangle_params_52(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_54(arg0, arg1, ...) cortecs_mangle_params_53(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_55(arg0, arg1, ...) cortecs_mangle_params_54(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_56(arg0, arg1, ...) cortecs_mangle_params_55(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_57(arg0, arg1, ...) cortecs_mangle_params_56(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_58(arg0, arg1, ...) cortecs_mangle_params_57(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_59(arg0, arg1, ...) cortecs_mangle_params_58(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_60(arg0, arg1, ...) cortecs_mangle_params_59(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_61(arg0, arg1, ...) cortecs_mangle_params_60(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_62(arg0, arg1, ...) cortecs_mangle_params_61(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params_63(arg0, arg1, ...) cortecs_mangle_params_62(CONCAT_3(arg0, _0, arg1), __VA_ARGS__)
#define cortecs_mangle_params(...) OVERLOADED_MACRO_0(cortecs_mangle_params_, __VA_ARGS__)

#define cortecs_mangle_name_2(arg0, arg1) CONCAT_3(arg0, _, arg1)
#define cortecs_mangle_name_3(arg0, arg1, ...) cortecs_mangle_name_2(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_4(arg0, arg1, ...) cortecs_mangle_name_3(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_5(arg0, arg1, ...) cortecs_mangle_name_4(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_6(arg0, arg1, ...) cortecs_mangle_name_5(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_7(arg0, arg1, ...) cortecs_mangle_name_6(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_8(arg0, arg1, ...) cortecs_mangle_name_7(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_9(arg0, arg1, ...) cortecs_mangle_name_8(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_10(arg0, arg1, ...) cortecs_mangle_name_9(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_11(arg0, arg1, ...) cortecs_mangle_name_10(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_12(arg0, arg1, ...) cortecs_mangle_name_11(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_13(arg0, arg1, ...) cortecs_mangle_name_12(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_14(arg0, arg1, ...) cortecs_mangle_name_13(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_15(arg0, arg1, ...) cortecs_mangle_name_14(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_16(arg0, arg1, ...) cortecs_mangle_name_15(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_17(arg0, arg1, ...) cortecs_mangle_name_16(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_18(arg0, arg1, ...) cortecs_mangle_name_17(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_19(arg0, arg1, ...) cortecs_mangle_name_18(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_20(arg0, arg1, ...) cortecs_mangle_name_19(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_21(arg0, arg1, ...) cortecs_mangle_name_20(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_22(arg0, arg1, ...) cortecs_mangle_name_21(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_23(arg0, arg1, ...) cortecs_mangle_name_22(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_24(arg0, arg1, ...) cortecs_mangle_name_23(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_25(arg0, arg1, ...) cortecs_mangle_name_24(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_26(arg0, arg1, ...) cortecs_mangle_name_25(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_27(arg0, arg1, ...) cortecs_mangle_name_26(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_28(arg0, arg1, ...) cortecs_mangle_name_27(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_29(arg0, arg1, ...) cortecs_mangle_name_28(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_30(arg0, arg1, ...) cortecs_mangle_name_29(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_31(arg0, arg1, ...) cortecs_mangle_name_30(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_32(arg0, arg1, ...) cortecs_mangle_name_31(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_33(arg0, arg1, ...) cortecs_mangle_name_32(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_34(arg0, arg1, ...) cortecs_mangle_name_33(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_35(arg0, arg1, ...) cortecs_mangle_name_34(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_36(arg0, arg1, ...) cortecs_mangle_name_35(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_37(arg0, arg1, ...) cortecs_mangle_name_36(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_38(arg0, arg1, ...) cortecs_mangle_name_37(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_39(arg0, arg1, ...) cortecs_mangle_name_38(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_40(arg0, arg1, ...) cortecs_mangle_name_39(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_41(arg0, arg1, ...) cortecs_mangle_name_40(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_42(arg0, arg1, ...) cortecs_mangle_name_41(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_43(arg0, arg1, ...) cortecs_mangle_name_42(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_44(arg0, arg1, ...) cortecs_mangle_name_43(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_45(arg0, arg1, ...) cortecs_mangle_name_44(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_46(arg0, arg1, ...) cortecs_mangle_name_45(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_47(arg0, arg1, ...) cortecs_mangle_name_46(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_48(arg0, arg1, ...) cortecs_mangle_name_47(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_49(arg0, arg1, ...) cortecs_mangle_name_48(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_50(arg0, arg1, ...) cortecs_mangle_name_49(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_51(arg0, arg1, ...) cortecs_mangle_name_50(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_52(arg0, arg1, ...) cortecs_mangle_name_51(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_53(arg0, arg1, ...) cortecs_mangle_name_52(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_54(arg0, arg1, ...) cortecs_mangle_name_53(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_55(arg0, arg1, ...) cortecs_mangle_name_54(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_56(arg0, arg1, ...) cortecs_mangle_name_55(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_57(arg0, arg1, ...) cortecs_mangle_name_56(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_58(arg0, arg1, ...) cortecs_mangle_name_57(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_59(arg0, arg1, ...) cortecs_mangle_name_58(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_60(arg0, arg1, ...) cortecs_mangle_name_59(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_61(arg0, arg1, ...) cortecs_mangle_name_60(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_62(arg0, arg1, ...) cortecs_mangle_name_61(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_mangle_name_63(arg0, arg1, ...) cortecs_mangle_name_62(CONCAT_3(arg0, _, arg1), __VA_ARGS__)
#define cortecs_name(...) OVERLOADED_MACRO_0(cortecs_mangle_name_, __VA_ARGS__)

// I also have no idea why it all works here. the C macro system is quite lovely...
#define cortecs_type_params(name, ...) CONCAT(name, _1, cortecs_mangle_params(__VA_ARGS__), _2)

#endif