cc_test(
    name = "log",
    size = "small",
    srcs = glob([
        "*.c",
    ]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/cortecs/log",
        "@unity",
    ],
)
