name: Approve calver
run-name: Approve calver
on:
  pull_request:
jobs:
  approve-calver:
    if: contains(github.event.pull_request.head.ref, 'version-bump/')
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment ${{github.event.pull_request.number}} --body "/trunk merge"