name: Run Required Checks
run-name: PR Checks for ${{ github.ref_name }}

# Trigger jobs whenever Trunk Merge tests a PR using a `trunk-merge/` branch
on:
  push:
    branches:
      - trunk-merge/**

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: All Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - run: bazel build //... --aspects @bazel_clang_tidy//clang_tidy:clang_tidy.bzl%clang_tidy_aspect --output_groups=report --@bazel_clang_tidy//:clang_tidy_config=//:clang_tidy_config
      - run: CC=clang bazel build //...
      - run: CC=gcc bazel coverage --instrumentation_filter //cortecs/... --combined_report=lcov //...
      - run: echo "COVERAGE_DAT=$(bazel info output_path)/_coverage/_coverage_report.dat" >> $GITHUB_ENV
      - run: echo $COVERAGE_DAT
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ${{ env.COVERAGE_DAT }}
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
          override_branch: main
