name: Update calver
run-name: Update calver
on:
  schedule:
    - cron: "19 6 * * *"
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  update-calver:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.x'
      - run: pip install GitPython
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: python .github/calver/update-calver.py
