name: Update calver
run-name: Update calver
on:
  schedule:
    - cron: "19 6 * * *"
env:
  GITHUB_TOKEN: ${{ github.token }}
  REUTERMJ_TOKEN: ${{ secrets.REUTERMJ_TOKEN }}
  # if this action start failing, you might need to update the above token
jobs:
  update-calver:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.x'
      - run: pip install GitPython
      - run: git config user.name "Mark Reuter"
      - run: git config user.email "13319190+reutermj@users.noreply.github.com"
      - run: python .github/calver/update-calver.py
